version: '3.8'

services:
  agendero-app:
    image: your-dockerhub-username/agendero:latest
    container_name: agendero-app
    ports:
      - "3000:3000"
    environment:
      - PORT=${PORT}
      - URL_LOGO=${URL_LOGO}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - Authentication__ApiKey=${Authentication__ApiKey}
      - URL_API=${URL_API}
    restart: unless-stopped
